[package]
name = "xrunner"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.3"

# existing bin (optional, if you want to keep running locally)
[[bin]]
name = "xrunner"
path = "src/main.rs"

